In [20]:
import numpy as np  

matriz_1 = np.random.uniform(     ## creacion de la matriz 1
    low=20,
    high=50, 
    size = (3,3) 
)   

matriz_1_enteros = matriz_1.round()


matriz_2 = np.random.uniform(      ## creacion de la matriz 2
    low=2000,
    high=5000, 
    size = (3,3) 
)   

matriz_2_enteros = matriz_2.round()  

display(
    matriz_1_enteros,
    matriz_2_enteros 
)

array([[28., 47., 42.],
       [29., 35., 37.],
       [45., 50., 23.]])

array([[4912., 4724., 3310.],
       [4908., 3813., 3243.],
       [4603., 4839., 2603.]])

In [19]:
matriz_1_9x1 = matriz_1_enteros.reshape(9,1)   # vuele la matriz en 9x1

matriz_2_9x1 = matriz_2_enteros.reshape(9,1)   # vuelve la matriz en 9x1

matriz_1_2_9x2 = np.column_stack((matriz_1_9x1,matriz_2_9x1))  # une las matrices 9x1

print(matriz_1_2_9x2)

[[  29. 2214.]
 [  44. 3333.]
 [  46. 3946.]
 [  45. 3589.]
 [  33. 4783.]
 [  22. 4015.]
 [  33. 3064.]
 [  26. 3442.]
 [  42. 3044.]]


In [50]:
entre_20_30 = matriz_1_2_9x2 < 30 

entre_2000_5000 = matriz_1_2_9x2 > 2000 

Salida = np.logical_or(entre_20_30 ,entre_2000_5000)

display (
  Salida
)

matriz_1_2_9x2[Salida]



array([[ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True]])

array([  29., 2214., 3333., 3946., 3589., 4783.,   22., 4015., 3064.,
         26., 3442., 3044.])